Fisi\SigriBundle\Entity\Actividad:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: '30'
            column: Titulo
        descripcion:
            type: string
            length: '250'
            column: Descripcion
        fechaEInicio:
            type: date
            column: Fecha_e_inicio
        fechaEFin:
            type: date
            column: Fecha_e_fin
        fechaRInicio:
            type: date
            column: Fecha_r_inicio
        fechaRFin:
            type: date
            column: Fecha_r_fin
        prioridad:
            type: string
            length: '5'
            column: Prioridad
        peso:
            type: integer
            column: Peso
        progreso:
            type: integer
            column: Progreso
    lifecycleCallbacks: {  }
