Fisi\SigriBundle\Entity\Avance:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fechaAvance:
            type: date
            column: Fecha_avance
        horaAvance:
            type: date
            column: Hora_avance
        descripcion:
            type: string
            length: '100'
            column: Descripcion
        progreso:
            type: integer
            column: Progreso
    lifecycleCallbacks: {  }
