Fisi\SigriBundle\Entity\Empleado:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '25'
            column: Nombre
        apellidoPaterno:
            type: string
            length: '25'
            column: Apellido_paterno
        apellidoMaterno:
            type: string
            length: '25'
            column: Apellido_materno
        telefono:
            type: string
            length: '9'
            column: Telefono
        email:
            type: string
            length: '25'
            column: Email
        direccion:
            type: string
            length: '75'
            column: Direccion
    lifecycleCallbacks: {  }
