Fisi\SigriBundle\Entity\Unidad_organica:
    type: entity
    table: null
    repositoryClass: Fisi\SigriBundle\Entity\Unidad_organicaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreUnidad:
            type: string
            length: '50'
            column: Nombre_unidad
        anexo:
            type: integer
            column: Anexo
    lifecycleCallbacks: {  }
