<?php

namespace Fisi\SigriBundle\Entity;

/**
 * Unidad_organicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Unidad_organicaRepository extends \Doctrine\ORM\EntityRepository
{
}
