fisi_sigri_homepage:
    path:     /
    defaults: { _controller: FisiSigriBundle:Default:index }
    
consultar_usuario:
    path:     /solicitante/consultar
    defaults: { _controller: FisiSigriBundle:User:ConsultarSolicitate }

solicitar_usuario:
    path:     /solicitante/solicitar
    defaults: { _controller: FisiSigriBundle:User:SolicitarSolicitante }
    
bandeja_entrada_gestor:
    path:     /gestor/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEG}
    
bandeja_entrada_personal:
    path:     /personal/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEP }
       

    
    
    
