fisi_sigri_admin_rol:
    resource: "@FisiSigriBundle/Resources/config/routing/rol.yml"
    prefix:   /admin/rol

fisi_sigri_admin_empleado:
    resource: "@FisiSigriBundle/Resources/config/routing/empleado.yml"
    prefix:   /admin/empleado

fisi_sigri_admin_personaloti:
    resource: "@FisiSigriBundle/Resources/config/routing/personaloti.yml"
    prefix:   /admin/personaloti
        
fisi_sigri_login:
    path:     /login
    defaults: { _controller: FisiSigriBundle:Default:login }
    
fisi_sigri_login_check:
    path:     /login_check
    defaults: { _controller: FisiSigriBundle:Default:login }
    
fisi_sigri_logout:
    path:     /logout    

fisi_sigri_homepage:
    path:     /
    defaults: { _controller: FisiSigriBundle:Default:index }
    
fisi_sigri_admin_menu:
    path: /admin/menu
    defaults: { _controller: FisiSigriBundle:Default:AdminMenu }
    
    
solicitudes_usuario:
    path:     /solicitante/solicitudes
    defaults: { _controller: FisiSigriBundle:User:SolicitudesSolicitante }

solicitud_usuario:
    path:     /solicitante/solicitud
    defaults: { _controller: FisiSigriBundle:User:Solicitud }

solicitud_calificar:
    path:     /solicitante/calificar
    defaults: { _controller: FisiSigriBundle:User:SolicitudCalificar }

notificaciones_usuario:
    path:     /solicitante/notificaciones
    defaults: { _controller: FisiSigriBundle:User:NotificacionesSolicitate }
    
solicitar_usuario:
    path:     /solicitante/solicitar
    defaults: { _controller: FisiSigriBundle:User:SolicitarSolicitante }
    
bandeja_entrada_gestor:
    path:     /gestor/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEG}
    
bandeja_entrada_personal:
    path:     /personal/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEP }

gestionar_actividad_personal:
    path:     /gestionActividad/bandeja
    defaults: { _controller: FisiSigriBundle:User:GestionarActividad}

menu_principal:
    path:   /gestor/menuPrincipal
    defaults: {_controller: FisiSigriBundle:Ticket:menuPrincipal}

bandeja_entrada_gestor_m:
    path: /gestor/menuPrincipal/bandejaEntrada
    defaults: {_controller: FisiSigriBundle:Ticket:bandejaEntradaGestor}
    
detalle_solicitud_gestor:
    path: /gestor/menuPrincipal/bandejaEntrada/detalleSolicitud
    defaults: {_controller: FisiSigriBundle:Ticket:detalleSoliicitudGestor}
    
agregarFilaGestor:
    path: /gestor/agregarFilaGestor
    defaults: {_controller: FisiSigriBundle:Ticket:agregarFilaGestor}
    
agregarFilaRespGestor:
    path: /gestor/agregarFilaRespGestor
    defaults: {_controller: FisiSigriBundle:Ticket:agregarFilaRespGestor}

bandejaAlertasGestor:
    path: /gestor/menuPrincipal/bandejaAlertas
    defaults: {_controller: FisiSigriBundle:Ticket:bandejaAlertasGestor}

  
actividadesGestor:
    path:   /gestor/menuPrincipal/actividades
    defaults: {_controller: FisiSigriBundle:Ticket:actividadesGestor}

seguimientoGestor:
    path:   /gestor/menuPrincipal/seguimiento
    defaults: {_controller: FisiSigriBundle:Ticket:seguimientoGestor}

manteminientoCatalogoGestor:
    path:   /gestor/menuPrincipal/mantenimientoCatalogo
    defaults: {_controller: FisiSigriBundle:Ticket:mantenimientoCatalogoGestor}

registrarCategoriaV:
    path:   /gestor/registrarCategoria
    defaults: {_controller: FisiSigriBundle:Ticket:registrarCategoriaV}

editarCategoriaV:
    path:   /gestor/editarCategoria
    defaults: {_controller: FisiSigriBundle:Ticket:editarCategoriaV}

eliminarCategoriaV:
    path:   /gestor/eliminarCategoria
    defaults: {_controller: FisiSigriBundle:Ticket:eliminarCategoriaV}

reportesGestor:
    path:   /gestor/menuPrincipal/reportes
    defaults: {_controller: FisiSigriBundle:Ticket:reportesGestor}

mantenimientoPersonal:
    path:   /gestor/menuPrincipal/manteminientoPersonal
    defaults: {_controller: FisiSigriBundle:Ticket:mantenimientoPersonal}
