fisi_sigri_admin_rol:
    resource: "@FisiSigriBundle/Resources/config/routing/rol.yml"
    prefix:   /admin/rol

fisi_sigri_admin_empleado:
    resource: "@FisiSigriBundle/Resources/config/routing/empleado.yml"
    prefix:   /admin/empleado

fisi_sigri_admin_personaloti:
    resource: "@FisiSigriBundle/Resources/config/routing/personaloti.yml"
    prefix:   /admin/personaloti
        
fisi_sigri_login:
    path:     /login
    defaults: { _controller: FisiSigriBundle:Default:login }
    
fisi_sigri_login_check:
    path:     /login_check
    defaults: { _controller: FisiSigriBundle:Default:login }
    
fisi_sigri_logout:
    path:     /logout    

fisi_sigri_homepage:
    path:     /
    defaults: { _controller: FisiSigriBundle:Default:index }
    
fisi_sigri_admin_menu:
    path: /admin/menu
    defaults: { _controller: FisiSigriBundle:Default:AdminMenu }
    
    
solicitudes_usuario:
    path:     /solicitante/solicitudes
    defaults: { _controller: FisiSigriBundle:User:SolicitudesSolicitante }

solicitud_usuario:
    path:     /solicitante/solicitud
    defaults: { _controller: FisiSigriBundle:User:Solicitud }

solicitud_calificar:
    path:     /solicitante/calificar
    defaults: { _controller: FisiSigriBundle:User:SolicitudCalificar }

notificaciones_usuario:
    path:     /solicitante/notificaciones
    defaults: { _controller: FisiSigriBundle:User:NotificacionesSolicitate }
    
solicitar_usuario:
    path:     /solicitante/solicitar
    defaults: { _controller: FisiSigriBundle:User:SolicitarSolicitante }
    
bandeja_entrada_gestor:
    path:     /gestor/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEG}
    
bandeja_entrada_personal:
    path:     /personal/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEP }

gestionar_actividad_personal:
    path:     /gestionActividad/bandeja
    defaults: { _controller: FisiSigriBundle:User:GestionarActividad}

menu_principal:
    path:   /gestor/menuPrincipal
    defaults: {_controller: FisiSigriBundle:Ticket:menuPrincipal}

bandeja_entrada_gestor_m:
    path: /gestor/menuPrincipal/bandejaEntrada
    defaults: {_controller: FisiSigriBundle:Ticket:bandejaEntradaGestor}
    
