fisi_sigri_homepage:
    path:     /
    defaults: { _controller: FisiSigriBundle:Default:index }
    
solicitudes_usuario:
    path:     /solicitante/solicitudes
    defaults: { _controller: FisiSigriBundle:User:SolicitudesSolicitante }

notificaciones_usuario:
    path:     /solicitante/notificaciones
    defaults: { _controller: FisiSigriBundle:User:NotificacionesSolicitate }
    
solicitar_usuario:
    path:     /solicitante/solicitar
    defaults: { _controller: FisiSigriBundle:User:SolicitarSolicitante }
    
bandeja_entrada_gestor:
    path:     /gestor/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEG}
    
bandeja_entrada_personal:
    path:     /personal/bandeja
    defaults: { _controller: FisiSigriBundle:User:MostrarBEP }

gestionar_actividad_personal:
    path:     /gestionActividad/bandeja
    defaults: { _controller: FisiSigriBundle:User:GestionarActividad}

menu_principal:
    path:   /gestor/menuPrincipal
    defaults: {_controller: FisiSigriBundle:Ticket:menuPrincipal}

    
    
    
